### ISSUE TITLE
Todo command

### ISSUE THREAD

**Issue by chaejinkeyne** [CS2103AUG2016-W15-C1/TaskRuby#16]
list uncompleted tasks only

**Comment by spaghetti-** [comment]
@elijahsk can I check if this needs to be done or should I just alias this command to a stub of addCommand?

**Comment by jasperlee27** [comment]
@spaghetti- think we're leaving out this command.

**Comment by chaejinkeyne** [comment]
please confirm, i'll need to update the docs accordingly

**Comment by chaejinkeyne** [comment]
not included in final submission
