### ISSUE TITLE
To reset Task ID after certain # or time

### ISSUE THREAD

**Issue by jasperlee27** [CS2103AUG2016-W15-C1/TaskRuby#31]
#30

Should we reset identifier so that we can start from Task ID 1 again?

**Comment by spaghetti-** [comment]
Sounds good - as of now when the user deletes the task the id is not reset (as intended) but with a `clear` command it should be done. 

Once the review of #30 is done we're good.

Take a look at https://github.com/CS2103AUG2016-W15-C1/TaskRuby/commit/4c65c040dad0b68d766cd00425604652e2553904 for usage.

**Comment by jasperlee27** [comment]
Done
